name: Offboarding de usuarios
run-name: baja de usuarios
on:
  workflow_dispatch:
    inputs:
      username:
        description: 'GitHub username del miembro a dar de baja'
        required: true
        type: string
      org:
        description: "Nombre de la organización"
        required: true
        type: string

jobs:
  remove-user:
    runs-on: ubuntu-latest

    steps:
      - name: Auth gh con token
        env:
          GH_TOKEN1: ${{ secrets.GH_TOKEN }}
        run: |
          echo "$GH_TOKEN1" | gh auth login --with-token

      - name: Generar auditoría de equipos/repos del usuario
        run: |
          ORG="${{ inputs.org }}"
          USER="${{ inputs.username }}"

          echo "Generando auditoría de accesos de $USER..."
          echo "### Auditoría de $USER" > auditoria_${USER}.md
          echo "- Organización: $ORG" >> auditoria_${USER}.md
          echo "- Usuario: $USER" >> auditoria_${USER}.md
          echo "- Fecha: $(date '+%Y-%m-%d %H:%M:%S')" >> auditoria_${USER}.md
          echo "" >> auditoria_${USER}.md

          echo "Equipos:"
          gh api "/orgs/$ORG/teams" --jq ".[] | select(.members_url | contains(\"$USER\")) | .slug" >> auditoria_${USER}.md || echo "Ninguno" >> auditoria_${USER}.md

          echo "" >> auditoria_${USER}.md
          echo "Repositorios (se obtienen por equipos relacionados)" >> auditoria_${USER}.md

          cat auditoria_${USER}.md

      - name: Eliminar usuario de la organización
        run: |
          ORG="${{ inputs.org }}"
          USER="${{ inputs.username }}"

          echo "Eliminando a $USER de la organización $ORG..."
          gh api --method DELETE "/orgs/$ORG/members/$USER" || echo "Usuario ya no está en la organización"
          echo "Baja completada"
