name: Offboarding Usuarios
run-name: Pruebas de baja de usuarios!
on:
  workflow_dispatch:
    inputs:
      username:
        description: "GitHub username a remover (sin @)"
        required: true
        type: string
      repo:
        description: "Repositorio para registrar auditoría"
        required: true
        type: string
      remove_from_org:
        description: "Eliminar de la org? (yes/no)"
        required: false
        default: "no"
        type: string

jobs:
  offboarding:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      issues: write
    steps:
      - name: Instalar gh
        run: |
          sudo apt-get update && sudo apt-get install -y curl jq
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo apt-get update && sudo apt-get install -y gh

      - name: Auth gh
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: echo "$GH_TOKEN" | gh auth login --with-token

      - name: Enumerar equipos y remover usuario
        env:
          ORG: ${{ github.repository_owner }}
        run: |
          USER="${{ inputs.username }}"
          echo "Buscando equipos de ${USER}"
          for team in $(gh api /orgs/$ORG/teams --jq '.[].slug'); do
            if gh api /orgs/$ORG/teams/$team/memberships/$USER >/dev/null 2>&1; then
              echo "Removiendo $USER del team $team"
              gh api --method DELETE /orgs/$ORG/teams/$team/memberships/$USER || true
            fi
          done

      - name: Revocar colaborador directo en todos los repos (org)
        env:
          ORG: ${{ github.repository_owner }}
        run: |
          USER="${{ inputs.username }}"
          for repo in $(gh api /orgs/$ORG/repos --jq '.[].name'); do
            if gh api /repos/$ORG/$repo/collaborators/$USER >/dev/null 2>&1; then
              echo "Revocando colaborador $USER en $repo"
              gh api --method DELETE /repos/$ORG/$repo/collaborators/$USER || true
            fi
          done

      - name: (Opcional) Eliminar de la organización
        if: ${{ inputs.remove_from_org == 'yes' }}
        env:
          ORG: ${{ github.repository_owner }}
        run: |
          gh api --method DELETE /orgs/$ORG/members/${{ inputs.username }} || true

      - name: Crear issue de auditoría en repo
        env:
          ORG: ${{ github.repository_owner }}
        run: |
          gh issue create --repo $ORG/${{ inputs.repo }} \
            --title "🔒 Offboarding completado para @${{ inputs.username }}" \
            --body "Se removió a **@${{ inputs.username }}** de todos los teams y colaboraciones. Fecha: $(date -u) UTC" || true
